favicon: null
name: trapp
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9699936143588275
  brandStrength: 0.7319544202182442
  lightness: 0.1471934248693287
  brandColors:
    - '#0D151E'
    - '#65A2D0'
    - '#91654B'
    - '#CEAD88'
    - '#547691'
  rhythmicContrast: 0.8873841899912804
typography_spectrum: 0.3976007830351591
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1279750445391983
analytics:
  twitter: null
  google: null
  facebook: null
