name: trapp
favicon: null
layout_spectrum: 0.12797504453919828
typography_spectrum: 0.3976007830351591
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7319544202182442
  lightness: 0.14719342486932874
  saturation: 0.9699936143588275
  rhythmicContrast: 0.8873841899912804
purpose: []
